# Generated by Django 6.0.1 on 2026-01-12 08:55

import pdf_engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='expire_at',
            field=models.DateTimeField(default=pdf_engine.models.default_expire),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='file',
            field=models.FileField(upload_to=pdf_engine.models.upload_to_shared),
        ),
    ]
