# Generated by Django 6.0.1 on 2026-01-12 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_engine', '0002_sharedfile_expire_at_alter_sharedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 13, 10, 9, 3, 935666, tzinfo=datetime.timezone.utc)),
        ),
    ]
