# Generated by Django 6.0.1 on 2026-01-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_engine', '0003_alter_sharedfile_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='expire_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='file',
            field=models.FileField(upload_to='shared/'),
        ),
    ]
